const actionTypes = {
  LOAD_PROJECTS_LIST: 'LOAD_PROJECTS_LIST',
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  ERROR_HANDLER: 'ERROR_HANDLER',
  GET_PROJECT_DETAIL: 'GET_PROJECT_DETAIL',
};

export default actionTypes;
